"""Initial migration

Revision ID: 118ff12b74b0
Revises: 
Create Date: 2023-01-22 13:59:28.589481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '118ff12b74b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('numbers',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('divisors',
    sa.Column('divisor', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number'], ['numbers.number'], ),
    sa.PrimaryKeyConstraint('divisor', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('divisors')
    op.drop_table('numbers')
    # ### end Alembic commands ###
