"""Initial schema

Revision ID: 8bfff52e52c4
Revises: 
Create Date: 2023-01-27 17:20:27.194150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8bfff52e52c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbers',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('divisors',
    sa.Column('divisor', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number'], ['numbers.number'], ),
    sa.PrimaryKeyConstraint('divisor', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divisors')
    op.drop_table('numbers')
    # ### end Alembic commands ###
